# Generated by Django 5.0.9 on 2024-09-10 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=60)),
                ('nro', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('apellido', models.CharField(max_length=500)),
                ('nacionalidad', models.CharField(max_length=18)),
                ('codigo_identidad', models.CharField(max_length=16)),
                ('sexo', models.BooleanField()),
                ('celular', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=60)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unido/a en Pareja de Hecho', 'Unido/a en Pareja de Hecho'), ('Separado/a', 'Separado/a'), ('En una Relacion de Pareja (No Formalizada)', 'En una Relacion de Pareja (No Formalizada)')], max_length=42)),
                ('escolaridad', models.CharField(choices=[('Sin Estudios', 'Sin Estudios'), ('Primaria Incompleta', 'Primaria Incompleta'), ('Primaria Completa', 'Primaria Completa'), ('Secundaria Incompleta', 'Secundaria Incompleta'), ('Secundaria Completa', 'Secundaria Completa'), ('Terciario/Universitario Incompleto', 'Terciario/Universitario Incompleto'), ('Terciario/Universitario Completo', 'Terciario/Universitario Completo')], max_length=34)),
                ('servicio_militar', models.BooleanField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('residencia_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencia_actual', to='appointment.domicilios')),
                ('residencia_habitual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencia_habitual', to='appointment.domicilios')),
            ],
        ),
        migrations.CreateModel(
            name='ObrasSocialesXPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.obrassociales')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asistio', 'Asistio'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado')], max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.pacientes')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profesionales')),
            ],
        ),
    ]
