# Generated by Django 5.0.9 on 2024-09-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asistio', 'Asistio'), ('Cancelado', 'Cancelado'), ('Reprogramado', 'Reprogramado')], max_length=15)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.pacientes')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profesionales')),
            ],
        ),
    ]
