# Generated by Django 5.0.7 on 2024-08-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contactos',
        ),
    ]
