# Generated by Django 5.0.9 on 2024-09-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=60)),
                ('nro', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.localidades')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('codigo_identidad', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=60)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unido/a en Pareja de Hecho', 'Unido/a en Pareja de Hecho'), ('Separado/a', 'Separado/a'), ('En una Relacion de Pareja (No Formalizada)', 'En una Relacion de Pareja (No Formalizada)')], max_length=50)),
                ('escolaridad', models.CharField(choices=[('Sin Estudios', 'Sin Estudios'), ('Primaria Incompleta', 'Primaria Incompleta'), ('Primaria Completa', 'Primaria Completa'), ('Secundaria Incompleta', 'Secundaria Incompleta'), ('Secundaria Completa', 'Secundaria Completa'), ('Terciario/Universitario Incompleto', 'Terciario/Universitario Incompleto'), ('Terciario/Universitario Completo', 'Terciario/Universitario Completo')], max_length=40)),
                ('servicio_militar', models.CharField(choices=[('Y', 'Si'), ('N', 'No')], max_length=1)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('residencia_actual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia_actual', to='patient.domicilios')),
                ('residencia_habitual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia_habitual', to='patient.domicilios')),
            ],
        ),
        migrations.CreateModel(
            name='ObrasSocialesXPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.obrassociales')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.paises')),
            ],
        ),
        migrations.AddField(
            model_name='localidades',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.provincias'),
        ),
        migrations.AddField(
            model_name='domicilios',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.provincias'),
        ),
    ]
